### ISSUE TITLE
STOMP is connecting to the server but receiving connection error from ActiveMQ 5.4.1

### ISSUE THREAD

**Issue by johnboyer** [juretta/objc-stomp#4]
I'm connecting but I receive this error from the server. Do you know what's going wrong?

Thank you, John Boyer

CONNECT
passcode:*******
login:username

org.apache.activemq.transport.stomp.ProtocolException: Allready connected. at org.apache.activemq.transport.stomp.ProtocolConverter.onStompConnect(ProtocolConverter.java:478)
    at org.apache.activemq.transport.stomp.ProtocolConverter.onStompCommand(ProtocolConverter.java:192)
    at org.apache.activemq.transport.stomp.StompTransportFilter.onCommand(StompTransportFilter.java:70)
    at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
    at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:219)
    at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:201)
    at java.lang.Thread.run(Thread.java:637)

**Comment by juretta** [comment]
Could you post the code you are using on the client side?

**Comment by johnboyer** [comment]
Thanks Stefan:

User error, our STOMP client code was auto connecting and we were explicitly connecting as well. Everything works fine now.

Regards,
John Boyer

**Comment by juretta** [comment]
Hi John,

Good to hear that it works for you!

Cheers,
Stefan
